### ISSUE TITLE
Support for generic SN3218 (such as piglow)

### ISSUE THREAD

**Issue by nicholas-gh** [pimoroni/pivumeter#13]
I plan to add support for both piglow (https://shop.pimoroni.com/products/piglow) and ws2812b based LED strips. For the piglow, I thought maybe almost nothing is needed, since the README.md (https://github.com/pimoroni/pivumeter/blob/8bddc3e94d996bf745d43a854793ca70b7bda12f/README.md#output_device) mentions:

> default (18-segment VU driven by SN3218)

However, I don't find any such support (for example, https://github.com/pimoroni/pivumeter/blob/8bddc3e94d996bf745d43a854793ca70b7bda12f/src/pivumeter.c doesn't allow 'default' as a valid output device type, and grep for sn3218 finds nothing). I've looked through history to see if support was removed, but I don't find that happening.

Is the mention in the README.md a plan that didn't happen yet, or do I miss some option/flag? 

Thank you!

**Comment by Gadgetoid** [comment]
Yes, if I remember correctly this was planned, but then I began the shift from the C front-end, to using Python instead which opens up a whole new avenue of support for Pi VU Meter- allowing anyone to add their own devices without needing to mess with C and recompile the plugin.

We need to get our own installer moved over to the new way of doing things.

If you want to be on the cutting edge, see the devel branch: https://github.com/pimoroni/pivumeter/tree/devel

And, more specifically, the Python-based library that connects to the new "socket" back-end. A basic example is here: https://github.com/pimoroni/pivumeter/blob/devel/python_server/examples/blinkt-server.py

**Comment by nicholas-gh** [comment]
Thanks for clarification. I'll look into -devel. For now, I've provided PR to update the README.md
