### ISSUE TITLE
pivumeter and dmixer do not work together

### ISSUE THREAD

**Issue by nicokaiser** [pimoroni/pivumeter#27]
I am looking for a way to use pivumeter with a pHAT DAC. This works fine, however only with one single sound source.

Since the pHAT DAC (just like the HiFiBerry) does not have a hardware mixer, I need to use the ALSA ´dmix` plugin, which also works fine per se.

Now when I try to combine both, I struggle. Since I cannot set a non-hardware device as slave for dmix I need to route the output through pivumeter first and the to dmixer:

```
pcm.!default {
        type plug
        slave.pcm "softvol_and_pivumeter"
}

ctl.!default {
        type hw
        card 0
}

pcm.pivumeter {
        type meter
        #slave.pcm "hw:0,0"
        slave.pcm "dmixer"
        scopes.0 pivumeter
}

pcm.softvol_and_pivumeter {
        type softvol
        slave.pcm "pivumeter"
        control {
                name "PCM"
                card 0
        }
}

pcm_scope.pivumeter {
        type pivumeter
        decay_ms 500
        peak_ms 400
        brightness 128
        output_device phat-beat
}

pcm_scope_type.pivumeter {
        lib /usr/local/lib/libpivumeter.so
}

pcm.dsp0 pivumeter

pcm.dmixer {
        type dmix
        ipc_key 1024
        ipc_key_add_uid false
        ipc_perm 0666
        slave {
                pcm "hw:0,0"
                period_time 0
                period_size 1024
                buffer_size 8192
                #rate 44100
                #format S16_LE
        }
        bindings {
                0 0
                1 1
        }
}
```

But with this config, there is no pivumeter output. Do you have an idea on how to solve this?

**Comment by nicokaiser** [comment]
With the above config, `aplay` hangs or crashes occasionally. I could trace this up to the point where the `level_ops` are called in a different order when using `dmix` (start, reset, update, update ... vs. start, update, reset, update …), but I'm a bit stuck here.

**Comment by Gadgetoid** [comment]
I had a similar problem with Pi VU Meter and dmix not playing well together, I think you've got closer to getting to the bottom of it than me, though.

I can't remember what exactly was going awry, but I think there were instances when Pi VU Meter was attempting to access a sample buffer that had been destroyed.

I didn't know where to go next, since debugging this sort of stuff really pushes the limits of my C knowledge.

**Comment by nicokaiser** [comment]
I tried to reproduce this with a minimal version of pivumeter/ameter (that only provides the functions and does nothing), but did not find any documentation about how `meter` plugins in ALSA are supposed to work (and with my complete lack of C knowledge I stopped at this point).

**Comment by Gadgetoid** [comment]
Closing this for now, with the hope of finding some time to explore a better, more robust alternative based around Pulse Audio (which I believe is now included in Raspberry Pi OS)!
