### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by apjavel** [pimoroni/pivumeter#3]
Hey guys,
It might well be my own fault,  but I can't get it to work with my pi3 and scrollphat. I installed according to instructions and copy/pasted your example asound.conf but edited to add scrollphat as output. Nothing happening when playing different audio. Do I need to do something else to the asound.conf? I have no soundcard attached. Cheers.

**Comment by Gadgetoid** [comment]
There's now an included `setup.sh` which may get you up and running.

It's all still a little rough around the edges, though. A pre-compiled version will come soon!

Also depending on your audio setup, your asound.conf may have to vary. It's a complicated beast!
