### ISSUE TITLE
pHat DAC option...

### ISSUE THREAD

**Issue by SalvorinFex** [pimoroni/pivumeter#5]
This is more of a request/inquiry, can this VU meter be used with the pHat DAC board?

That would make an awesome combo.

**Comment by RogueM** [comment]
sure... you can use a blinkt for example, support is built-in.

**Comment by Gadgetoid** [comment]
The VU meter isn't opinionated about your audio output- you could use a Scroll pHAT or Blinkt with regular onboard audio if you wanted!
