### ISSUE TITLE
DOT hat bargraph

### ISSUE THREAD

**Issue by Worthless-Inventions** [pimoroni/pivumeter#9]
Would you be able to implement the vu meter for the DOT hat bargraph

from my testing it seems to use the led dirver on the cap1166

these would be usefull for when I am playing something and have info about it on the screen.

**Comment by Gadgetoid** [comment]
I'm looking at switching to a fifo-based method which will process the audio and pipe it out so Python can pick it up and work with it. This should make it much, much easier to add support for new devices and avoid multiple scripts clobbering each other when they try to access the same hardware.
